// GitHub PR Utilities for AccessGuard
// Helper functions for creating PRs with accessibility fixes

import type { Violation } from '@/types';

// Generate a branch name for accessibility fixes
export function createFixBranchName(ruleId: string, timestamp?: Date): string {
  const ts = timestamp || new Date();
  const dateStr = ts.toISOString().split('T')[0].replace(/-/g, '');
  const timeStr = ts.getTime().toString(36);
  const sanitizedRuleId = ruleId.toLowerCase().replace(/[^a-z0-9]/g, '-').slice(0, 30);
  
  return `accessguard/fix-${sanitizedRuleId}-${dateStr}-${timeStr}`;
}

// Generate a PR title from violations
export function generatePrTitle(violations: Violation[]): string {
  if (violations.length === 0) {
    return 'AccessGuard: Accessibility fixes';
  }
  
  const ruleIds = [...new Set(violations.map(v => v.ruleId))];
  
  if (ruleIds.length === 1) {
    const ruleName = ruleIds[0].replace(/-/g, ' ').replace(/\b\w/g, l => l.toUpperCase());
    return `fix(a11y): ${ruleName} (${violations.length} occurrence${violations.length > 1 ? 's' : ''})`;
  }
  
  const criticalCount = violations.filter(v => v.severity === 'critical').length;
  const seriousCount = violations.filter(v => v.severity === 'serious').length;
  
  if (criticalCount > 0) {
    return `fix(a11y): ${violations.length} accessibility issues (${criticalCount} critical)`;
  }
  
  if (seriousCount > 0) {
    return `fix(a11y): ${violations.length} accessibility issues (${seriousCount} serious)`;
  }
  
  return `fix(a11y): ${violations.length} accessibility improvements`;
}

// Generate PR body with violation details
export function generatePrBody(violations: Violation[], project?: { name: string; url: string }): string {
  const lines: string[] = [
    '## AccessGuard - Accessibility Fixes',
    '',
    'This PR was automatically generated by [AccessGuard](https://accessguard.io) to address accessibility issues.',
    '',
  ];
  
  if (project) {
    lines.push(`**Project:** ${project.name}`);
    lines.push(`**URL:** ${project.url}`);
    lines.push('');
  }
  
  // Summary
  const critical = violations.filter(v => v.severity === 'critical').length;
  const serious = violations.filter(v => v.severity === 'serious').length;
  const moderate = violations.filter(v => v.severity === 'moderate').length;
  const minor = violations.filter(v => v.severity === 'minor').length;
  
  lines.push('### Summary');
  lines.push('');
  lines.push(`- **Total Issues:** ${violations.length}`);
  if (critical > 0) lines.push(`- **Critical:** ${critical}`);
  if (serious > 0) lines.push(`- **Serious:** ${serious}`);
  if (moderate > 0) lines.push(`- **Moderate:** ${moderate}`);
  if (minor > 0) lines.push(`- **Minor:** ${minor}`);
  lines.push('');
  
  // Group violations by rule
  const violationsByRule = violations.reduce((acc, v) => {
    if (!acc[v.ruleId]) acc[v.ruleId] = [];
    acc[v.ruleId].push(v);
    return acc;
  }, {} as Record<string, Violation[]>);
  
  lines.push('### Issues Fixed');
  lines.push('');
  
  for (const [ruleId, ruleViolations] of Object.entries(violationsByRule)) {
    const ruleName = ruleId.replace(/-/g, ' ').replace(/\b\w/g, l => l.toUpperCase());
    lines.push(`#### ${ruleName}`);
    lines.push('');
    
    for (const v of ruleViolations.slice(0, 5)) { // Limit to 5 per rule for readability
      lines.push(`- **[${v.severity.toUpperCase()}]** ${v.description}`);
      lines.push(`  - Location: ${v.url}`);
      if (v.elementSelector) {
        lines.push(`  - Selector: \`${v.elementSelector}\``);
      }
      lines.push('');
    }
    
    if (ruleViolations.length > 5) {
      lines.push(`_... and ${ruleViolations.length - 5} more occurrences_`);
      lines.push('');
    }
  }
  
  // WCAG Criteria
  const wcagCriteria = [...new Set(violations.map(v => v.wcagCriteria).filter(Boolean))];
  if (wcagCriteria.length > 0) {
    lines.push('### WCAG Criteria Addressed');
    lines.push('');
    lines.push(wcagCriteria.map(c => `- WCAG ${c}`).join('\n'));
    lines.push('');
  }
  
  // Footer
  lines.push('---');
  lines.push('');
  lines.push('_This PR was created by AccessGuard. Please review the changes carefully before merging._');
  lines.push('');
  lines.push('**Recommendations:**');
  lines.push('- Review each fix for correctness');
  lines.push('- Test with screen readers');
  lines.push('- Verify no regressions in functionality');
  
  return lines.join('\n');
}

// Apply fixes to file content
export function applyFixesToFile(
  originalContent: string,
  violations: Violation[],
  filePath: string
): { content: string; fixesApplied: number; errors: string[] } {
  const errors: string[] = [];
  let content = originalContent;
  let fixesApplied = 0;
  
  // Sort violations by position (if we had it) - for now, just apply in order
  // Group violations by element selector
  const violationsBySelector = violations.reduce((acc, v) => {
    if (v.elementSelector && v.remediationCode) {
      if (!acc[v.elementSelector]) acc[v.elementSelector] = [];
      acc[v.elementSelector].push(v);
    }
    return acc;
  }, {} as Record<string, Violation[]>);
  
  for (const [selector, selectorViolations] of Object.entries(violationsBySelector)) {
    // For now, we'll create a comment block with the fixes
    // A real implementation would parse the file and apply changes
    const fixComment = generateFixComment(selector, selectorViolations, filePath);
    
    // Simple approach: add fixes as comments at the top of the file
    // This is safer and allows developers to review and apply manually
    if (!content.includes('AccessGuard Accessibility Fixes')) {
      content = fixComment + '\n\n' + content;
      fixesApplied += selectorViolations.length;
    }
  }
  
  return { content, fixesApplied, errors };
}

// Generate a fix comment block
function generateFixComment(
  selector: string,
  violations: Violation[],
  filePath: string
): string {
  const lines: string[] = [];
  
  // Determine file type for comment syntax
  const ext = filePath.split('.').pop()?.toLowerCase();
  const commentStart = ['js', 'jsx', 'ts', 'tsx', 'css', 'scss', 'sass'].includes(ext || '') 
    ? '/*' 
    : '<!--';
  const commentEnd = ['js', 'jsx', 'ts', 'tsx', 'css', 'scss', 'sass'].includes(ext || '') 
    ? '*/' 
    : '-->';
  const lineComment = ['js', 'jsx', 'ts', 'tsx'].includes(ext || '') ? '//' : '#';
  
  lines.push(`${commentStart}`);
  lines.push(' * AccessGuard Accessibility Fixes');
  lines.push(' * ');
  lines.push(` * Element: ${selector}`);
  lines.push(` * File: ${filePath}`);
  lines.push(' * ');
  lines.push(' * Issues Found:');
  
  for (const v of violations) {
    lines.push(` * - [${v.severity.toUpperCase()}] ${v.ruleId}: ${v.description}`);
  }
  
  lines.push(' * ');
  lines.push(' * Suggested Fixes:');
  
  for (const v of violations) {
    if (v.remediationCode) {
      lines.push(' * ---');
      lines.push(` * Rule: ${v.ruleId}`);
      if (v.aiExplanation) {
        lines.push(` * Explanation: ${v.aiExplanation}`);
      }
      lines.push(' * Code:');
      for (const codeLine of v.remediationCode.split('\n')) {
        lines.push(` *   ${codeLine}`);
      }
    }
  }
  
  lines.push(`${commentEnd}`);
  
  return lines.join('\n');
}

// Parse GitHub PR URL
export function parsePrUrl(url: string): { owner: string; repo: string; pullNumber: number } | null {
  const match = url.match(/github\.com\/([^/]+)\/([^/]+)\/pull\/(\d+)/);
  if (!match) return null;
  
  return {
    owner: match[1],
    repo: match[2],
    pullNumber: parseInt(match[3], 10),
  };
}

// Generate preview content for demo mode
export function generateDemoPreview(violations: Violation[]): {
  branchName: string;
  prTitle: string;
  prBody: string;
  filesToModify: string[];
} {
  const branchName = createFixBranchName('accessibility-fixes');
  const prTitle = generatePrTitle(violations);
  const prBody = generatePrBody(violations);
  
  // Get unique file paths from element selectors (simplified)
  const filesToModify = [...new Set(
    violations
      .map(v => v.url)
      .filter(Boolean)
      .map(url => {
        try {
          const path = new URL(url).pathname;
          return path === '/' ? 'index.html' : `${path}.html`;
        } catch {
          return 'index.html';
        }
      })
  )].slice(0, 5);
  
  return {
    branchName,
    prTitle,
    prBody,
    filesToModify,
  };
}
