// GitHub PR Utilities for AccessGuard
// Helper functions for creating PRs with accessibility fixes

import type { Severity } from '@/types';
import { validateFixForRule } from '@/lib/fix-validation';

// Flexible violation type that works with both strict types and Prisma results
export type ViolationForPR = {
  id: string;
  ruleId: string;
  severity: Severity | string;
  url: string;
  description: string;
  wcagCriteria?: string | null;
  elementSelector?: string | null;
  elementHtml?: string | null;
  remediationCode?: string | null;
  aiExplanation?: string | null;
  project?: { name: string; url: string };
};

// Minimal shape required for file-level fix application
export type FileFixViolation = {
  ruleId: string;
  severity?: string;
  description?: string;
  elementSelector?: string | null;
  elementHtml?: string | null;
  remediationCode?: string | null;
  aiExplanation?: string | null;
};

// Generate a branch name for accessibility fixes
export function createFixBranchName(ruleId: string, timestamp?: Date): string {
  const ts = timestamp || new Date();
  const dateStr = ts.toISOString().split('T')[0].replace(/-/g, '');
  const timeStr = ts.getTime().toString(36);
  const sanitizedRuleId = ruleId.toLowerCase().replace(/[^a-z0-9]/g, '-').slice(0, 30);
  
  return `accessguard/fix-${sanitizedRuleId}-${dateStr}-${timeStr}`;
}

// Generate a PR title from violations
export function generatePrTitle(violations: ViolationForPR[]): string {
  if (violations.length === 0) {
    return 'AccessGuard: Accessibility fixes';
  }
  
  const ruleIds = [...new Set(violations.map(v => v.ruleId))];
  
  if (ruleIds.length === 1) {
    const ruleName = ruleIds[0].replace(/-/g, ' ').replace(/\b\w/g, l => l.toUpperCase());
    return `fix(a11y): ${ruleName} (${violations.length} occurrence${violations.length > 1 ? 's' : ''})`;
  }
  
  const criticalCount = violations.filter(v => v.severity === 'critical').length;
  const seriousCount = violations.filter(v => v.severity === 'serious').length;
  
  if (criticalCount > 0) {
    return `fix(a11y): ${violations.length} accessibility issues (${criticalCount} critical)`;
  }
  
  if (seriousCount > 0) {
    return `fix(a11y): ${violations.length} accessibility issues (${seriousCount} serious)`;
  }
  
  return `fix(a11y): ${violations.length} accessibility improvements`;
}

// Generate PR body with violation details
export function generatePrBody(violations: ViolationForPR[], project?: { name: string; url: string }): string {
  const lines: string[] = [
    '## AccessGuard - Accessibility Fixes',
    '',
    'This PR was automatically generated by [AccessGuard](https://accessguard.io) to address accessibility issues.',
    '',
  ];
  
  if (project) {
    lines.push(`**Project:** ${project.name}`);
    lines.push(`**URL:** ${project.url}`);
    lines.push('');
  }
  
  // Summary
  const critical = violations.filter(v => v.severity === 'critical').length;
  const serious = violations.filter(v => v.severity === 'serious').length;
  const moderate = violations.filter(v => v.severity === 'moderate').length;
  const minor = violations.filter(v => v.severity === 'minor').length;
  
  lines.push('### Summary');
  lines.push('');
  lines.push(`- **Total Issues:** ${violations.length}`);
  if (critical > 0) lines.push(`- **Critical:** ${critical}`);
  if (serious > 0) lines.push(`- **Serious:** ${serious}`);
  if (moderate > 0) lines.push(`- **Moderate:** ${moderate}`);
  if (minor > 0) lines.push(`- **Minor:** ${minor}`);
  lines.push('');
  
  // Group violations by rule
  const violationsByRule = violations.reduce((acc, v) => {
    if (!acc[v.ruleId]) acc[v.ruleId] = [];
    acc[v.ruleId].push(v);
    return acc;
  }, {} as Record<string, ViolationForPR[]>);
  
  lines.push('### Issues Fixed');
  lines.push('');
  
  for (const [ruleId, ruleViolations] of Object.entries(violationsByRule)) {
    const ruleName = ruleId.replace(/-/g, ' ').replace(/\b\w/g, l => l.toUpperCase());
    lines.push(`#### ${ruleName}`);
    lines.push('');
    
    for (const v of ruleViolations.slice(0, 5)) { // Limit to 5 per rule for readability
      lines.push(`- **[${v.severity.toUpperCase()}]** ${v.description}`);
      lines.push(`  - Location: ${v.url}`);
      if (v.elementSelector) {
        lines.push(`  - Selector: \`${v.elementSelector}\``);
      }
      lines.push('');
    }
    
    if (ruleViolations.length > 5) {
      lines.push(`_... and ${ruleViolations.length - 5} more occurrences_`);
      lines.push('');
    }
  }
  
  // WCAG Criteria
  const wcagCriteria = [...new Set(violations.map(v => v.wcagCriteria).filter(Boolean))];
  if (wcagCriteria.length > 0) {
    lines.push('### WCAG Criteria Addressed');
    lines.push('');
    lines.push(wcagCriteria.map(c => `- WCAG ${c}`).join('\n'));
    lines.push('');
  }
  
  // Footer
  lines.push('---');
  lines.push('');
  lines.push('_This PR was created by AccessGuard. Please review the changes carefully before merging._');
  lines.push('');
  lines.push('**Recommendations:**');
  lines.push('- Review each fix for correctness');
  lines.push('- Test with screen readers');
  lines.push('- Verify no regressions in functionality');
  
  return lines.join('\n');
}

// Validate AI-generated remediation code before applying it to source files
export function validateRemediation(
  remediationCode: string | null | undefined,
  originalElementHtml?: string | null
): { valid: boolean; reason?: string } {
  if (!remediationCode || !remediationCode.trim()) {
    return { valid: false, reason: 'empty remediation code' };
  }

  const code = remediationCode.trim();

  if (code.length > 20_000) {
    return { valid: false, reason: 'remediation code exceeds 20k characters' };
  }

  // No script injection
  if (/<script[\s>]/i.test(code)) {
    return { valid: false, reason: 'remediation code introduces a <script> tag' };
  }

  // No javascript: URI injection
  if (/["']\s*javascript:\s*/i.test(code) || /\bjavascript:\/\//i.test(code)) {
    return { valid: false, reason: 'remediation code contains a javascript: URI' };
  }

  // No event-handler injection if the original element had none
  const newHandlers = [...code.matchAll(/\son[a-z]+="?/gi)].map((m) => m[0].toLowerCase());
  const originalHandlers = originalElementHtml
    ? [...originalElementHtml.matchAll(/\son[a-z]+="?/gi)].map((m) => m[0].toLowerCase())
    : [];

  const injectedHandlers = newHandlers.filter((h) => !originalHandlers.includes(h));
  if (injectedHandlers.length > 0) {
    return { valid: false, reason: `injects new event handler: ${injectedHandlers[0]}` };
  }

  // No unclosed HTML tags (rough balance check for common void-safe tags)
  const tagNames = [...new Set([...code.matchAll(/<\/?([a-z][a-z0-9-]*)\b/gi)].map((m) => m[1].toLowerCase()))];
  const voidTags = new Set(['area', 'base', 'br', 'col', 'embed', 'hr', 'img', 'input', 'link', 'meta', 'param', 'source', 'track', 'wbr']);
  for (const tag of tagNames) {
    if (voidTags.has(tag)) continue;
    const open = (code.match(new RegExp(`<${tag}(\\s[^>]*)?(?<!/)>`, 'gi')) || []).length;
    const close = (code.match(new RegExp(`</${tag}\\s*>`, 'gi')) || []).length;
    if (open > close) {
      return { valid: false, reason: `unclosed <${tag}> tag in remediation code` };
    }
  }

  return { valid: true };
}

// Apply fixes to file content
export function applyFixesToFile(
  originalContent: string,
  violations: FileFixViolation[],
  filePath: string
): { content: string; fixesApplied: number; errors: string[] } {
  const errors: string[] = [];
  let content = originalContent;
  let fixesApplied = 0;
  const unmatched: FileFixViolation[] = [];

  for (const v of violations) {
    if (!v.remediationCode) continue;

    const validation = validateRemediation(v.remediationCode, v.elementHtml);
    if (!validation.valid) {
      errors.push(`[${v.ruleId}] skipped: ${validation.reason}`);
      continue;
    }

    const ruleCheck = validateFixForRule(v.ruleId, v.remediationCode, v.elementHtml);
    if (!ruleCheck.valid) {
      errors.push(`[${v.ruleId}] skipped (does not fix rule): ${ruleCheck.reason}`);
      continue;
    }

    if (!v.elementHtml) {
      unmatched.push(v);
      continue;
    }

    // 1. Exact match replacement
    if (content.includes(v.elementHtml)) {
      content = content.replace(v.elementHtml, v.remediationCode);
      fixesApplied++;
      continue;
    }

    // 2. Trimmed match (leading/trailing whitespace differences)
    const trimmedElem = v.elementHtml.trim();
    const trimmedFix = v.remediationCode.trim();
    if (trimmedElem && content.includes(trimmedElem)) {
      content = content.replace(trimmedElem, trimmedFix);
      fixesApplied++;
      continue;
    }

    unmatched.push(v);
  }

  // Fallback for violations we could not apply: attach review comments at the top
  if (unmatched.length > 0) {
    const fixComment = generateFixComment(filePath, unmatched);
    if (!content.includes('AccessGuard Accessibility Fixes')) {
      content = fixComment + '\n\n' + content;
    }
  }

  return { content, fixesApplied, errors };
}

// Generate a fix comment block
function generateFixComment(
  filePath: string,
  violations: FileFixViolation[]
): string {
  const lines: string[] = [];
  
  // Determine file type for comment syntax
  const ext = filePath.split('.').pop()?.toLowerCase();
  const commentStart = ['js', 'jsx', 'ts', 'tsx', 'css', 'scss', 'sass'].includes(ext || '') 
    ? '/*' 
    : '<!--';
  const commentEnd = ['js', 'jsx', 'ts', 'tsx', 'css', 'scss', 'sass'].includes(ext || '') 
    ? '*/' 
    : '-->';
  const lineComment = ['js', 'jsx', 'ts', 'tsx'].includes(ext || '') ? '//' : '#';
  
  lines.push(`${commentStart}`);
  lines.push(' * AccessGuard Accessibility Fixes');
  lines.push(' * ');
  lines.push(` * File: ${filePath}`);
  lines.push(' * ');
  lines.push(' * Issues Found:');
  
  for (const v of violations) {
    lines.push(` * - [${(v.severity || 'N/A').toUpperCase()}] ${v.ruleId}: ${v.description || 'Accessibility violation'}`);
  }
  
  lines.push(' * ');
  lines.push(' * Suggested Fixes:');
  
  for (const v of violations) {
    if (v.remediationCode) {
      lines.push(' * ---');
      lines.push(` * Rule: ${v.ruleId}`);
      if (v.aiExplanation) {
        lines.push(` * Explanation: ${v.aiExplanation}`);
      }
      lines.push(' * Code:');
      for (const codeLine of v.remediationCode.split('\n')) {
        lines.push(` *   ${codeLine}`);
      }
    }
  }
  
  lines.push(`${commentEnd}`);
  
  return lines.join('\n');
}

// Parse GitHub PR URL
export function parsePrUrl(url: string): { owner: string; repo: string; pullNumber: number } | null {
  const match = url.match(/github\.com\/([^/]+)\/([^/]+)\/pull\/(\d+)/);
  if (!match) return null;
  
  return {
    owner: match[1],
    repo: match[2],
    pullNumber: parseInt(match[3], 10),
  };
}

// Generate preview content for demo mode
export function generateDemoPreview(violations: ViolationForPR[]): {
  branchName: string;
  prTitle: string;
  prBody: string;
  filesToModify: string[];
} {
  const branchName = createFixBranchName('accessibility-fixes');
  const prTitle = generatePrTitle(violations);
  const prBody = generatePrBody(violations);
  
  // Get unique file paths from element selectors (simplified)
  const filesToModify = [...new Set(
    violations
      .map(v => v.url)
      .filter(Boolean)
      .map(url => {
        try {
          const path = new URL(url).pathname;
          return path === '/' ? 'index.html' : `${path}.html`;
        } catch {
          return 'index.html';
        }
      })
  )].slice(0, 5);
  
  return {
    branchName,
    prTitle,
    prBody,
    filesToModify,
  };
}
