import { db } from '@/lib/db';
import { notFound } from 'next/navigation';
import { Shield, Globe, AlertTriangle, CheckCircle2, XCircle, EyeOff, Sparkles, Clock } from 'lucide-react';

interface SharedSummary {
  projectName: string;
  projectUrl: string;
  orgName: string;
  generatedAt: string;
  severity: { critical: number; serious: number; moderate: number; minor: number; total: number };
  status: { open: number; fixed: number; ignored: number };
  totalViolations: number;
  aiFixRate: number;
  lastScanAt: string | null;
}

export default async function SharedReportPage({ params }: { params: Promise<{ token: string }> }) {
  const { token } = await params;

  const reports = await db.complianceReport.findMany({ take: 100 });
  const report = reports.find((r) => {
    try {
      const meta = JSON.parse(r.metadata || '{}');
      return meta.shareToken === token;
    } catch {
      return false;
    }
  });

  if (!report) {
    notFound();
  }

  let summary: SharedSummary | null = null;
  try {
    summary = report.summary ? (JSON.parse(report.summary) as SharedSummary) : null;
  } catch {
    summary = null;
  }

  return (
    <div className="min-h-screen bg-background">
      <header className="border-b border-border">
        <div className="max-w-3xl mx-auto px-6 py-6 flex items-center gap-3">
          <Shield className="h-7 w-7 text-coral" />
          <div>
            <h1 className="text-lg font-bold leading-tight">AccessGuard Compliance Report</h1>
            <p className="text-xs text-muted-foreground">Generated by {summary?.orgName || 'AccessGuard'}</p>
          </div>
          <div className="ml-auto flex items-center gap-1.5 text-xs text-muted-foreground">
            <Clock className="h-3.5 w-3.5" />
            {summary?.generatedAt ? new Date(summary.generatedAt).toLocaleDateString() : '—'}
          </div>
        </div>
      </header>

      <main className="max-w-3xl mx-auto px-6 py-10 space-y-8">
        <div>
          <div className="flex items-center gap-2 mb-1">
            <Globe className="h-4 w-4 text-muted-foreground" />
            <a
              href={summary?.projectUrl}
              target="_blank"
              rel="noopener noreferrer"
              className="text-sm text-coral hover:underline"
            >
              {summary?.projectUrl}
            </a>
          </div>
          <h2 className="text-2xl font-bold">{summary?.projectName || 'Project'}</h2>
        </div>

        {summary && (
          <>
            <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
              <div className="p-4 rounded-xl border border-border bg-card">
                <p className="text-3xl font-bold">{summary.totalViolations}</p>
                <p className="text-xs text-muted-foreground mt-1">Total violations</p>
              </div>
              <div className="p-4 rounded-xl border border-border bg-card">
                <p className="text-3xl font-bold">{summary.severity.critical}</p>
                <p className="text-xs text-red-500 mt-1">Critical</p>
              </div>
              <div className="p-4 rounded-xl border border-border bg-card">
                <p className="text-3xl font-bold">{summary.status.fixed}</p>
                <p className="text-xs text-emerald-500 mt-1">Fixed</p>
              </div>
              <div className="p-4 rounded-xl border border-border bg-card">
                <p className="text-3xl font-bold">{summary.aiFixRate}%</p>
                <p className="text-xs text-coral mt-1">AI fix rate</p>
              </div>
            </div>

            <section className="space-y-3">
              <h3 className="font-semibold">Open Violations by Severity</h3>
              <div className="space-y-2">
                {[
                  { label: 'Critical', value: summary.severity.critical, color: 'bg-red-500' },
                  { label: 'Serious', value: summary.severity.serious, color: 'bg-orange-500' },
                  { label: 'Moderate', value: summary.severity.moderate, color: 'bg-yellow-500' },
                  { label: 'Minor', value: summary.severity.minor, color: 'bg-blue-500' },
                ].map((row) => (
                  <div key={row.label} className="flex items-center gap-3">
                    <span className="w-20 text-sm text-muted-foreground">{row.label}</span>
                    <div className="flex-1 h-2.5 rounded-full bg-muted overflow-hidden">
                      <div
                        className={`h-full rounded-full ${row.color}`}
                        style={{ width: `${summary.severity.total > 0 ? (row.value / summary.severity.total) * 100 : 0}%` }}
                      />
                    </div>
                    <span className="w-8 text-right text-sm font-medium">{row.value}</span>
                  </div>
                ))}
              </div>
            </section>

            <section className="p-5 rounded-xl border border-border bg-card space-y-3">
              <h3 className="font-semibold flex items-center gap-2">
                <Sparkles className="h-4 w-4 text-coral" />
                Remediation Status
              </h3>
              <div className="grid grid-cols-3 gap-3 text-center">
                <div>
                  <CheckCircle2 className="h-5 w-5 text-emerald-500 mx-auto mb-1" />
                  <p className="text-lg font-bold">{summary.status.fixed}</p>
                  <p className="text-xs text-muted-foreground">Fixed</p>
                </div>
                <div>
                  <AlertTriangle className="h-5 w-5 text-orange-500 mx-auto mb-1" />
                  <p className="text-lg font-bold">{summary.status.open}</p>
                  <p className="text-xs text-muted-foreground">Open</p>
                </div>
                <div>
                  <EyeOff className="h-5 w-5 text-gray-400 mx-auto mb-1" />
                  <p className="text-lg font-bold">{summary.status.ignored}</p>
                  <p className="text-xs text-muted-foreground">Ignored</p>
                </div>
              </div>
            </section>

            {summary.lastScanAt && (
              <p className="text-xs text-muted-foreground">
                Last completed scan: {new Date(summary.lastScanAt).toLocaleString()}
              </p>
            )}
          </>
        )}

        <footer className="pt-6 border-t border-border text-center">
          <p className="text-xs text-muted-foreground">
            Generated by AccessGuard — ADA / WCAG 2.1 AA compliance monitoring
          </p>
        </footer>
      </main>
    </div>
  );
}
