import { NextRequest, NextResponse } from 'next/server';
import { db } from '@/lib/db';
import { logger } from '@/lib/error-logger';
import { requireOrgAccess } from '@/lib/rbac';
import { PERMISSIONS } from '@/lib/permissions';

interface GitHubPRRequest {
  orgId: string;
  repository: string;
  branch: string;
  files: Array<{
    path: string;
    content: string;
    message: string;
  }>;
  title: string;
  body: string;
}

// POST - Create a PR with accessibility fixes
export async function POST(request: NextRequest) {
  try {
    const body: GitHubPRRequest = await request.json();
    const { orgId, repository, branch, files, title, body: prBody } = body;

    if (!orgId || !repository || !files || files.length === 0) {
      return NextResponse.json(
        { success: false, error: 'Missing required fields' },
        { status: 400 }
      );
    }

    const access = await requireOrgAccess(request, orgId, { permission: PERMISSIONS.CREATE_PR });
    if (access instanceof NextResponse) return access;

    // Get GitHub connection
    const connection = await db.githubConnection.findFirst({
      where: { orgId: access.org.id, isActive: true },
    });

    if (!connection) {
      return NextResponse.json(
        { success: false, error: 'GitHub not connected. Please connect your GitHub account first.' },
        { status: 400 }
      );
    }

    // Whitelist repository against the org's connected repositories (prevents cross-tenant / arbitrary repo writes)
    const allowedRepos: string[] = connection.repositories
      ? (JSON.parse(connection.repositories) as Array<{ fullName?: string }> | null)
          ?.map((r) => r.fullName)
          .filter((n: unknown): n is string => typeof n === 'string') ?? []
      : [];
    if (allowedRepos.length === 0 || !allowedRepos.includes(repository)) {
      return NextResponse.json(
        { success: false, error: 'Repository is not part of your connected GitHub repositories' },
        { status: 403 }
      );
    }

    // In production, retrieve the actual OAuth token from secure storage
    const token = process.env.GITHUB_TOKEN;
    if (!token) {
      return NextResponse.json(
        { success: false, error: 'GitHub integration not configured. Please set GITHUB_TOKEN.' },
        { status: 500 }
      );
    }

    const headers = {
      'Authorization': `Bearer ${token}`,
      'Accept': 'application/vnd.github.v3+json',
      'X-GitHub-Api-Version': '2022-11-28',
    };

    // Get repository info
    const repoResponse = await fetch(`https://api.github.com/repos/${repository}`, { headers });
    if (!repoResponse.ok) {
      return NextResponse.json(
        { success: false, error: 'Repository not found or no access' },
        { status: 404 }
      );
    }
    const repoData = await repoResponse.json();
    const defaultBranch = repoData.default_branch;

    // Get latest commit on default branch
    const refResponse = await fetch(
      `https://api.github.com/repos/${repository}/git/refs/heads/${defaultBranch}`,
      { headers }
    );
    const refData = await refResponse.json();
    const baseSha = refData.object.sha;

    // Create a new branch
    const branchName = branch || `accessibility-fixes-${Date.now()}`;
    await fetch(`https://api.github.com/repos/${repository}/git/refs`, {
      method: 'POST',
      headers,
      body: JSON.stringify({
        ref: `refs/heads/${branchName}`,
        sha: baseSha,
      }),
    });

    // Create blobs and tree for each file
    for (const file of files) {
      // Get the file's current SHA (if exists)
      let fileSha: string | null = null;
      try {
        const fileResponse = await fetch(
          `https://api.github.com/repos/${repository}/contents/${file.path}?ref=${branchName}`,
          { headers }
        );
        if (fileResponse.ok) {
          const fileData = await fileResponse.json();
          fileSha = fileData.sha;
        }
      } catch {
        // File doesn't exist, will create new
      }

      // Create or update the file
      const content = Buffer.from(file.content).toString('base64');
      await fetch(`https://api.github.com/repos/${repository}/contents/${file.path}`, {
        method: 'PUT',
        headers,
        body: JSON.stringify({
          message: file.message,
          content,
          branch: branchName,
          sha: fileSha || undefined,
        }),
      });
    }

    // Create pull request
    const prResponse = await fetch(`https://api.github.com/repos/${repository}/pulls`, {
      method: 'POST',
      headers,
      body: JSON.stringify({
        title: title || 'Accessibility Fixes',
        body: prBody || `## Accessibility Improvements

This PR contains accessibility fixes generated by AccessGuard.

### Changes
${files.map(f => `- 📝 \`${f.path}\`: ${f.message}`).join('\n')}

### How to Review
1. Review each file change
2. Test with a screen reader if possible
3. Verify the fixes don't break existing functionality

---
*Generated by [AccessGuard](https://accessguard.io)*`,
        head: branchName,
        base: defaultBranch,
      }),
    });

    if (!prResponse.ok) {
      const errorData = await prResponse.json();
      throw new Error(errorData.message || 'Failed to create PR');
    }

    const prData = await prResponse.json();

    // Create audit log
    await db.auditLog.create({
      data: {
        orgId,
        action: 'github_pr_created',
        metadata: JSON.stringify({
          repository,
          branch: branchName,
          prNumber: prData.number,
          prUrl: prData.html_url,
          fileCount: files.length,
        }),
      },
    });

    return NextResponse.json({
      success: true,
      data: {
        pullRequest: {
          number: prData.number,
          url: prData.html_url,
          branch: branchName,
        },
      },
    });
  } catch (error) {
    logger.error({ err: error }, '');
    return NextResponse.json(
      { success: false, error: error instanceof Error ? error.message : 'Failed to create PR' },
      { status: 500 }
    );
  }
}

// GET - List connected repositories
export async function GET(request: NextRequest) {
  try {
    const { searchParams } = new URL(request.url);
    const orgId = searchParams.get('orgId');

    const access = await requireOrgAccess(request, orgId);
    if (access instanceof NextResponse) return access;

    const connection = await db.githubConnection.findFirst({
      where: { orgId: access.org.id, isActive: true },
    });

    if (!connection) {
      return NextResponse.json({
        success: true,
        data: {
          connected: false,
          repositories: [],
        },
      });
    }

    const repositories = JSON.parse(connection.repositories || '[]');

    return NextResponse.json({
      success: true,
      data: {
        connected: true,
        repositories,
      },
    });
  } catch (error) {
    logger.error({ err: error }, '');
    return NextResponse.json(
      { success: false, error: 'Failed to fetch repositories' },
      { status: 500 }
    );
  }
}
