import { logger } from '@/lib/error-logger';
import {
  WCAG_RULES,
  getRuleInfo,
  buildSystemPrompt,
  buildUserPrompt,
  parseRemediationResponse,
  renderTemplateFix,
  type RemediationPromptInput,
} from '@/ai/prompts';
import { callChatCompletions, getModelConfigs, type ModelUsage } from '@/ai/model-router';
import { estimateCost, type CostEstimate } from '@/ai/cost';

interface RemediationRequest extends RemediationPromptInput {
  violationId: string;
}

export interface RemediationResult {
  remediationCode: string;
  explanation: string;
  confidence: number;
  source: 'llm' | 'template';
  model: string | null;
  usage: ModelUsage | null;
  costEstimate: CostEstimate | null;
}

// Re-export for the GET /api/remediate (WCAG rules reference)
export { WCAG_RULES };

export async function generateRemediation(violation: RemediationRequest): Promise<RemediationResult> {
  const configs = getModelConfigs();
  const llmEnabled = configs.some((c) => c.apiKey);

  if (!llmEnabled) {
    return templateResult(violation);
  }

  const messages = [
    { role: 'system' as const, content: buildSystemPrompt() },
    { role: 'user' as const, content: buildUserPrompt(violation) },
  ];

  const completion = await callChatCompletions(messages, configs);

  if (!completion) {
    logger.warn({ violationId: violation.violationId }, 'All AI providers failed; falling back to template remediation');
    return templateResult(violation);
  }

  const parsed = parseRemediationResponse(completion.content);
  const costEstimate = estimateCost(completion.model, completion.usage);

  logger.info(
    { violationId: violation.violationId, model: completion.model, usage: completion.usage, costEstimate },
    'AI remediation generated'
  );

  if (!parsed.remediationCode) {
    logger.warn({ violationId: violation.violationId }, 'LLM returned no code block; falling back to template');
    return templateResult(violation);
  }

  return {
    remediationCode: parsed.remediationCode,
    explanation: parsed.explanation || 'Generated by AI. Review the fix before applying.',
    confidence: parsed.confidence,
    source: 'llm',
    model: completion.model,
    usage: completion.usage,
    costEstimate,
  };
}

function templateResult(violation: RemediationRequest): RemediationResult {
  const rule = getRuleInfo(violation.ruleId, violation.description);
  const fix = renderTemplateFix(violation.elementHtml, violation.ruleId, violation.description);
  return {
    remediationCode: fix.remediationCode,
    explanation: `${fix.explanation} Rule: ${rule.name} (${violation.wcagCriteria}).`,
    confidence: 0.5,
    source: 'template',
    model: null,
    usage: null,
    costEstimate: null,
  };
}